version: '3'
services:
  app:
    build:
      context: .
    command: >
      sh -c "bundle install &&
      rails db:create &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    restart: always
    ports:
      - "4000:3000"
    volumes:
      - ${PWD}:/usr/src/app
    depends_on:
      - db
  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rails